import ExcelJS from "exceljs";

import type { StudentComprehensiveReport } from "./student-comprehensive-report.service";

const BORDER_COLOR = "FFDCE2EA";
const NAVY = "FF172033";
const SLATE = "FF64748B";

const SECTION_PALETTES = [
  { accent: "FF4F46E5", light: "FFEEF2FF", tab: "FF6366F1" },
  { accent: "FF7C3AED", light: "FFF5F3FF", tab: "FF8B5CF6" },
  { accent: "FF0369A1", light: "FFF0F9FF", tab: "FF0EA5E9" },
  { accent: "FF047857", light: "FFECFDF5", tab: "FF10B981" },
  { accent: "FFB45309", light: "FFFFFBEB", tab: "FFF59E0B" },
  { accent: "FFBE123C", light: "FFFFF1F2", tab: "FFF43F5E" },
  { accent: "FF0F766E", light: "FFF0FDFA", tab: "FF14B8A6" },
  { accent: "FF475569", light: "FFF8FAFC", tab: "FF64748B" },
  { accent: "FF6D28D9", light: "FFFAF5FF", tab: "FFA855F7" },
] as const;

const POSITIVE_STATUSES = new Set(["ACTIVE", "PRESENT", "PAID", "PASS", "PASSED", "SUCCESS", "APPROVED"]);
const NEGATIVE_STATUSES = new Set(["ABSENT", "OVERDUE", "FAIL", "FAILED", "VOID", "VOIDED", "REJECTED"]);
const WARNING_STATUSES = new Set(["LATE", "PENDING", "PARTIAL", "ON_LEAVE", "DRAFT"]);

function columnWidth(header: string, values: unknown[]) {
  const longest = Math.max(
    header.length,
    ...values.map((value) => String(value ?? "").length),
  );
  return Math.min(Math.max(longest + 3, 12), 42);
}

export function createStudentComprehensiveWorkbook(
  report: StudentComprehensiveReport,
  generatedBy: string,
) {
  const workbook = new ExcelJS.Workbook();
  const generatedAt = new Date(report.generatedAt);
  workbook.creator = generatedBy;
  workbook.lastModifiedBy = generatedBy;
  workbook.created = generatedAt;
  workbook.subject = `Complete student report for ${report.studentName}`;
  workbook.keywords = `SchoolDB, student report, ${report.admissionNo}`;

  for (const [sectionIndex, section] of report.sections.entries()) {
    const palette = SECTION_PALETTES[sectionIndex % SECTION_PALETTES.length];
    const worksheet = workbook.addWorksheet(section.title.slice(0, 31), {
      properties: { tabColor: { argb: palette.tab }, defaultRowHeight: 19 },
      views: [{ state: "frozen", ySplit: 7, showGridLines: false }],
      pageSetup: {
        orientation: section.columns.length > 4 ? "landscape" : "portrait",
        paperSize: 9,
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        printTitlesRow: "1:7",
        margins: {
          left: 0.25,
          right: 0.25,
          top: 0.5,
          bottom: 0.5,
          header: 0.2,
          footer: 0.2,
        },
      },
    });
    const lastColumn = Math.max(section.columns.length, 1);
    for (let row = 1; row <= 5; row += 1) worksheet.mergeCells(row, 1, row, lastColumn);
    worksheet.getCell("A1").value = report.schoolName.toUpperCase();
    worksheet.getCell("A2").value = `${report.studentName.toUpperCase()} · COMPLETE STUDENT PORTFOLIO`;
    worksheet.getCell("A3").value = section.title.toUpperCase();
    worksheet.getCell("A4").value =
      `Admission No: ${report.admissionNo} | Generated: ${generatedAt.toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}`;
    worksheet.getCell("A5").value = "CONFIDENTIAL ACADEMIC RECORD · GENERATED BY SCHOOLDB";

    for (let column = 1; column <= lastColumn; column += 1) {
      worksheet.getCell(1, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
      worksheet.getCell(2, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
      worksheet.getCell(3, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: palette.accent } };
      worksheet.getCell(4, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: palette.light } };
      worksheet.getCell(5, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
    }
    worksheet.getRow(1).font = {
      bold: true,
      size: 18,
      color: { argb: "FFFFFFFF" },
    };
    worksheet.getRow(2).font = {
      bold: true,
      size: 12,
      color: { argb: "FFE0E7FF" },
    };
    worksheet.getRow(3).font = {
      bold: true,
      size: 13,
      color: { argb: "FFFFFFFF" },
    };
    worksheet.getRow(4).font = { bold: true, size: 10, color: { argb: NAVY } };
    worksheet.getRow(5).font = { bold: true, size: 8, color: { argb: SLATE } };
    for (let row = 1; row <= 5; row += 1) {
      worksheet.getRow(row).alignment = {
        horizontal: "center",
        vertical: "middle",
      };
    }
    worksheet.getRow(1).height = 32;
    worksheet.getRow(2).height = 24;
    worksheet.getRow(3).height = 27;
    worksheet.getRow(4).height = 23;
    worksheet.getRow(5).height = 19;
    worksheet.getRow(6).height = 9;

    section.columns.forEach((column, columnIndex) => {
      const cell = worksheet.getCell(7, columnIndex + 1);
      cell.value = column;
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: NAVY },
      };
      cell.alignment = {
        horizontal: "center",
        vertical: "middle",
        wrapText: true,
      };
      cell.border = {
        top: { style: "thin", color: { argb: BORDER_COLOR } },
        left: { style: "thin", color: { argb: BORDER_COLOR } },
        bottom: { style: "thin", color: { argb: BORDER_COLOR } },
        right: { style: "thin", color: { argb: BORDER_COLOR } },
      };
      worksheet.getColumn(columnIndex + 1).width = columnWidth(
        column,
        section.rows.map((row) => row[column]),
      );
    });
    worksheet.getRow(7).height = 30;

    section.rows.forEach((row, rowIndex) => {
      const excelRow = worksheet.getRow(rowIndex + 8);
      excelRow.height = 22;
      section.columns.forEach((column, columnIndex) => {
        const cell = excelRow.getCell(columnIndex + 1);
        cell.value = row[column] ?? "";
        cell.alignment = { vertical: "top", wrapText: true };
        cell.border = {
          top: { style: "hair", color: { argb: BORDER_COLOR } },
          left: { style: "hair", color: { argb: BORDER_COLOR } },
          bottom: { style: "hair", color: { argb: BORDER_COLOR } },
          right: { style: "hair", color: { argb: BORDER_COLOR } },
        };
        if (rowIndex % 2 === 1) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: palette.light },
          };
        }
        if (
          ["Payable", "Paid", "Outstanding"].includes(column) &&
          typeof cell.value === "number"
        ) {
          cell.numFmt = "₹#,##0.00";
          cell.alignment = { horizontal: "right", vertical: "top", wrapText: true };
        }
        if (["Marks Obtained", "Maximum Marks", "Pass Marks", "Size (KB)"].includes(column) && typeof cell.value === "number") {
          cell.numFmt = "#,##0.00";
          cell.alignment = { horizontal: "right", vertical: "top", wrapText: true };
        }
        if (["Status", "Exam Status", "Active"].includes(column) && typeof cell.value === "string") {
          const normalized = cell.value.toUpperCase();
          if (POSITIVE_STATUSES.has(normalized)) {
            cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFDCFCE7" } };
            cell.font = { bold: true, color: { argb: "FF166534" } };
          } else if (NEGATIVE_STATUSES.has(normalized)) {
            cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFEE2E2" } };
            cell.font = { bold: true, color: { argb: "FF991B1B" } };
          } else if (WARNING_STATUSES.has(normalized)) {
            cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFEF3C7" } };
            cell.font = { bold: true, color: { argb: "FF92400E" } };
          }
        }
      });
    });

    if (!section.rows.length) {
      worksheet.mergeCells(8, 1, 8, lastColumn);
      worksheet.getCell(8, 1).value =
        `No ${section.title.toLowerCase()} records available.`;
      worksheet.getCell(8, 1).alignment = {
        horizontal: "center",
        vertical: "middle",
      };
      worksheet.getCell(8, 1).font = {
        italic: true,
        color: { argb: SLATE },
      };
      worksheet.getCell(8, 1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: palette.light } };
      worksheet.getRow(8).height = 30;
    }

    worksheet.autoFilter = {
      from: { row: 7, column: 1 },
      to: { row: Math.max(section.rows.length + 7, 7), column: lastColumn },
    };
    worksheet.headerFooter.oddFooter = `&LConfidential · ${report.admissionNo}&C${report.studentName} · ${section.title}&RPage &P of &N`;
  }

  return workbook;
}
