"use client";

import { useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpFromLine, Boxes, CircleDollarSign, PackagePlus, Search, TriangleAlert, Warehouse } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { EmptyPanel, EntityCombobox, Field, formatCurrency, formatDate, MetricCard, OperationsData, Row, SelectField, StatusBadge, titleCase, useOperationMutation } from "./shared";

const categories = ["STATIONERY", "IT_EQUIPMENT", "LAB_EQUIPMENT", "FURNITURE", "SPORTS", "ELECTRICAL", "CLEANING", "TEACHING_AIDS", "UNIFORM", "OTHER"].map((value) => ({ value, label: titleCase(value) }));

export function InventoryManager({ data }: { data: OperationsData }) {
  const { pending, submit } = useOperationMutation();
  const items = useMemo(() => data.items ?? [], [data.items]);
  const [movementItem, setMovementItem] = useState("");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("ALL");
  const itemOptions = items.map((item) => ({ value: String(item.id), label: String(item.name), description: `${item.assetCode} · ${item.quantity} available` }));
  const totalUnits = items.reduce((sum, item) => sum + Number(item.quantity ?? 0), 0);
  const totalValue = items.reduce((sum, item) => sum + Number(item.quantity ?? 0) * Number(item.unitCost ?? 0), 0);
  const lowStock = items.filter((item) => Number(item.quantity) <= Number(item.reorderLevel));
  const filtered = useMemo(() => items.filter((item) => `${item.assetCode} ${item.name} ${item.category} ${item.location} ${item.custodian}`.toLowerCase().includes(query.toLowerCase()) && (category === "ALL" || item.category === category)), [category, items, query]);
  const recentMovements: Row[] = items
    .flatMap((item) => ((item.movements as Row[] | undefined) ?? []).map((movement) => ({ ...movement, itemName: item.name, assetCode: item.assetCode }) as Row))
    .sort((left, right) => String(right.createdAt).localeCompare(String(left.createdAt)))
    .slice(0, 15);
  return <div className="space-y-6 pb-10">
    <section className="rounded-3xl border border-amber-100 bg-gradient-to-br from-white via-amber-50/60 to-orange-50/50 p-6 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-700">Asset control</p><h2 className="mt-3 text-2xl font-bold">Every asset accounted for, from purchase to issue.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Maintain item codes, quantities, valuation, condition, custodian, warranty and a permanent inward/outward movement history.</p></div><div className="grid grid-cols-2 gap-3"><MetricCard label="Inventory items" value={items.length} icon={Boxes} /><MetricCard label="Stock value" value={formatCurrency(totalValue)} icon={CircleDollarSign} tone="emerald" /></div></div></section>
    <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Total units" value={totalUnits} icon={Warehouse} /><MetricCard label="Low-stock items" value={lowStock.length} icon={TriangleAlert} tone={lowStock.length ? "rose" : "emerald"} /><MetricCard label="Locations" value={new Set(items.map((item) => item.location).filter(Boolean)).size} icon={Warehouse} tone="amber" /></div>
    <Tabs defaultValue="register" className="space-y-5"><TabsList><TabsTrigger value="register">Asset register</TabsTrigger><TabsTrigger value="new">Add asset/item</TabsTrigger><TabsTrigger value="movement">Stock movement</TabsTrigger></TabsList>
      <TabsContent value="register" className="space-y-4"><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search code, item, location or custodian" /></div><SelectField name="inventoryCategoryFilter" placeholder="Filter category" value={category} onValueChange={setCategory} options={[{ value: "ALL", label: "All categories" }, ...categories]} /></div><InventoryTable rows={filtered} /></TabsContent>
      <TabsContent value="new"><Card><CardHeader><CardTitle>Add inventory item or fixed asset</CardTitle><CardDescription>Record purchasing, location, condition and reorder information at creation.</CardDescription></CardHeader><CardContent><form className="space-y-6" onSubmit={(event) => submit("CREATE_INVENTORY_ITEM", event, undefined, "Inventory item added.")}><section className="grid gap-4 md:grid-cols-3"><Field label="Asset / item code" required><Input name="assetCode" required maxLength={40} placeholder="IT-LAP-001" /></Field><Field label="Item name" required className="md:col-span-2"><Input name="name" required maxLength={160} placeholder="Dell Latitude laptop" /></Field><Field label="Category" required><SelectField name="category" placeholder="Choose category" options={categories} /></Field><Field label="Location"><Input name="location" maxLength={120} placeholder="Computer Lab 1" /></Field><Field label="Custodian"><Input name="custodian" maxLength={160} placeholder="Staff member or department" /></Field></section><section className="grid gap-4 rounded-2xl border p-4 md:grid-cols-3"><Field label="Opening quantity" required><Input name="quantity" type="number" min="0" defaultValue="1" required /></Field><Field label="Reorder level" required><Input name="reorderLevel" type="number" min="0" defaultValue="0" required /></Field><Field label="Unit cost (₹)"><Input name="unitCost" type="number" min="0" step="0.01" inputMode="decimal" /></Field><Field label="Condition" required><SelectField name="condition" placeholder="Choose condition" defaultValue="GOOD" options={["NEW", "GOOD", "FAIR", "POOR", "DAMAGED"].map((value) => ({ value, label: titleCase(value) }))} /></Field><Field label="Purchase date"><Input name="purchaseDate" type="date" /></Field><Field label="Warranty until"><Input name="warrantyUntil" type="date" /></Field></section><Button disabled={pending}><PackagePlus className="size-4" />Add inventory item</Button></form></CardContent></Card></TabsContent>
      <TabsContent value="movement"><div className="grid gap-5 xl:grid-cols-[0.75fr_1.25fr]"><Card><CardHeader><CardTitle>Record stock movement</CardTitle><CardDescription>Use inward for receipts, outward for issues, and adjustment for verified corrections.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => submit("ADJUST_INVENTORY", event, { itemId: movementItem }, "Stock balance updated.")}><Field label="Inventory item" required><EntityCombobox value={movementItem} onChange={setMovementItem} options={itemOptions} placeholder="Search item code or name" /></Field><Field label="Movement type" required><SelectField name="type" placeholder="Choose movement" options={[{ value: "IN", label: "Stock inward / received" }, { value: "OUT", label: "Stock outward / issued" }, { value: "ADJUSTMENT", label: "Positive stock adjustment" }]} /></Field><Field label="Quantity" required><Input name="quantity" type="number" min="1" required /></Field><Field label="Reference number"><Input name="reference" maxLength={120} placeholder="Invoice, issue slip or audit reference" /></Field><Field label="Movement notes"><Textarea name="notes" maxLength={500} placeholder="Vendor, recipient or reason for adjustment" /></Field><Button className="w-full" disabled={pending || !movementItem}><ArrowDownToLine className="size-4" />Record movement</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Recent item movements</CardTitle><CardDescription>The latest five movements are retained with each item below.</CardDescription></CardHeader><CardContent className="space-y-3">{recentMovements.map((row) => <div key={String(row.id)} className="flex items-center justify-between gap-4 rounded-2xl border p-4"><div className="flex items-center gap-3"><div className={`flex size-10 items-center justify-center rounded-xl ${row.type === "OUT" ? "bg-rose-50 text-rose-700" : "bg-emerald-50 text-emerald-700"}`}>{row.type === "OUT" ? <ArrowUpFromLine className="size-4" /> : <ArrowDownToLine className="size-4" />}</div><div><p className="font-semibold">{String(row.itemName)}</p><p className="text-xs text-muted-foreground">{String(row.assetCode)} · {formatDate(row.createdAt)}</p></div></div><div className="text-right"><p className="font-bold">{row.type === "OUT" ? "−" : "+"}{String(row.quantity)}</p><p className="text-xs text-muted-foreground">{titleCase(row.type)}</p></div></div>)}</CardContent></Card></div></TabsContent>
    </Tabs>
  </div>;
}

function InventoryTable({ rows }: { rows: Row[] }) { return <Card><CardContent className="p-0">{!rows.length ? <EmptyPanel title="No inventory items found" description="Add the first asset or change your search filters." /> : <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="border-y bg-muted/30"><tr>{["Code", "Item", "Category", "Location / custodian", "Stock", "Unit cost", "Total value", "Condition"].map((heading) => <th key={heading} className="px-5 py-3 text-left text-xs uppercase text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{rows.map((row) => { const low = Number(row.quantity) <= Number(row.reorderLevel); return <tr key={String(row.id)} className="border-b last:border-0"><td className="px-5 py-4 font-mono text-xs font-bold">{String(row.assetCode)}</td><td className="px-5 py-4 font-semibold">{String(row.name)}</td><td className="px-5 py-4"><Badge variant="outline">{titleCase(row.category)}</Badge></td><td className="px-5 py-4"><p>{String(row.location ?? "—")}</p><p className="text-xs text-muted-foreground">{String(row.custodian ?? "No custodian")}</p></td><td className="px-5 py-4"><Badge variant={low ? "destructive" : "success"}>{String(row.quantity)} units</Badge>{low ? <p className="mt-1 text-xs text-destructive">Reorder at {String(row.reorderLevel)}</p> : null}</td><td className="px-5 py-4">{formatCurrency(row.unitCost)}</td><td className="px-5 py-4 font-bold">{formatCurrency(Number(row.quantity) * Number(row.unitCost ?? 0))}</td><td className="px-5 py-4"><StatusBadge value={row.condition} /></td></tr>; })}</tbody></table></div>}</CardContent></Card>; }
