"use client";

import { FormEvent, useMemo, useState } from "react";
import { AlertOctagon, CircleDollarSign, ClipboardCheck, Search, Wrench } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EmptyPanel, Field, formatCurrency, formatDate, formValues, MetricCard, OperationsData, Row, SelectField, StatusBadge, titleCase, useOperationMutation } from "./shared";

const categories = ["ELECTRICAL", "PLUMBING", "CIVIL", "FURNITURE", "IT_EQUIPMENT", "LAB_EQUIPMENT", "TRANSPORT", "CLEANING", "SAFETY", "OTHER"].map((value) => ({ value, label: titleCase(value) }));
const statuses = ["OPEN", "IN_PROGRESS", "ON_HOLD", "RESOLVED", "CLOSED"].map((value) => ({ value, label: titleCase(value) }));

export function MaintenanceManager({ data }: { data: OperationsData }) {
  const { pending, mutate, submit } = useOperationMutation();
  const rows = useMemo(() => data.tickets ?? [], [data.tickets]);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [edit, setEdit] = useState<Row | null>(null);
  const open = rows.filter((row) => ["OPEN", "IN_PROGRESS", "ON_HOLD"].includes(String(row.status))).length;
  const urgent = rows.filter((row) => row.priority === "URGENT" && !["RESOLVED", "CLOSED"].includes(String(row.status))).length;
  const estimated = rows.filter((row) => !["RESOLVED", "CLOSED"].includes(String(row.status))).reduce((sum, row) => sum + Number(row.estimatedCost ?? 0), 0);
  const filtered = useMemo(() => rows.filter((row) => `${row.ticketNo} ${row.title} ${row.description} ${row.location} ${row.assignedTo}`.toLowerCase().includes(query.toLowerCase()) && (statusFilter === "ALL" || row.status === statusFilter)), [query, rows, statusFilter]);
  return <div className="space-y-6 pb-10">
    <section className="rounded-3xl border border-slate-200 bg-gradient-to-br from-white via-slate-50 to-blue-50/50 p-6 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-600">Facilities helpdesk</p><h2 className="mt-3 text-2xl font-bold">Report, assign and close every maintenance issue.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Track priority, category, location, owner, due date, estimated cost, actual cost and resolution details from one accountable register.</p></div><div className="grid grid-cols-2 gap-3"><MetricCard label="Open tickets" value={open} icon={Wrench} tone="amber" /><MetricCard label="Urgent" value={urgent} icon={AlertOctagon} tone={urgent ? "rose" : "emerald"} /></div></div></section>
    <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Total tickets" value={rows.length} icon={ClipboardCheck} /><MetricCard label="Outstanding estimate" value={formatCurrency(estimated)} icon={CircleDollarSign} tone="amber" /><MetricCard label="Resolved" value={rows.filter((row) => ["RESOLVED", "CLOSED"].includes(String(row.status))).length} icon={ClipboardCheck} tone="emerald" /></div>
    <div className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><Card><CardHeader><CardTitle>Report maintenance issue</CardTitle><CardDescription>Provide enough detail for assignment and cost planning.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => submit("CREATE_MAINTENANCE", event, undefined, "Maintenance ticket created.")}><Field label="Issue title" required><Input name="title" minLength={3} maxLength={180} required placeholder="Water leakage near primary washroom" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category" required><SelectField name="category" placeholder="Choose category" options={categories} /></Field><Field label="Priority" required><SelectField name="priority" placeholder="Choose priority" defaultValue="MEDIUM" options={["LOW", "MEDIUM", "HIGH", "URGENT"].map((value) => ({ value, label: titleCase(value) }))} /></Field><Field label="Location"><Input name="location" maxLength={120} placeholder="Block, floor and room" /></Field><Field label="Assign to"><Input name="assignedTo" maxLength={160} placeholder="Person, team or vendor" /></Field><Field label="Estimated cost (₹)"><Input name="estimatedCost" type="number" min="0" step="0.01" /></Field><Field label="Target completion"><Input name="dueDate" type="date" /></Field></div><Field label="Detailed description" required><Textarea name="description" minLength={3} maxLength={1500} required placeholder="Problem, impact, safety risk and any temporary action taken" rows={4} /></Field><Button className="w-full" disabled={pending}><Wrench className="size-4" />Create maintenance ticket</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Maintenance register</CardTitle><CardDescription>Search and filter tickets, then update ownership, cost and resolution.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-[1fr_190px]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ticket, issue or location" /></div><SelectField name="maintenanceStatusFilter" placeholder="Filter status" value={statusFilter} onValueChange={setStatusFilter} options={[{ value: "ALL", label: "All statuses" }, ...statuses]} /></div>{!filtered.length ? <EmptyPanel title="No maintenance tickets" description="Create the first ticket or change the filters." /> : <div className="space-y-3">{filtered.map((row) => <div key={String(row.id)} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-bold text-muted-foreground">{String(row.ticketNo)}</span><StatusBadge value={row.priority} /><StatusBadge value={row.status} /></div><h3 className="mt-2 font-bold">{String(row.title)}</h3><p className="mt-1 text-sm text-muted-foreground">{String(row.description)}</p></div><Button size="sm" variant="outline" onClick={() => setEdit(row)}>Update</Button></div><div className="mt-4 grid gap-2 border-t pt-4 text-xs text-muted-foreground sm:grid-cols-3"><span>Location: {String(row.location ?? "—")}</span><span>Assigned: {String(row.assignedTo ?? "Unassigned")}</span><span>Due: {formatDate(row.dueDate)}</span><span>Estimate: {formatCurrency(row.estimatedCost)}</span><span>Actual: {formatCurrency(row.actualCost)}</span><span>Created: {formatDate(row.createdAt)}</span></div></div>)}</div>}</CardContent></Card></div>
    <Dialog open={Boolean(edit)} onOpenChange={(open) => { if (!open) setEdit(null); }}><DialogContent><form key={String(edit?.id ?? "new")} onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!edit) return; const values = formValues(event.currentTarget); mutate("UPDATE_MAINTENANCE", { id: edit.id, ...values }, { success: "Maintenance ticket updated.", after: () => setEdit(null) }); }}><DialogHeader><DialogTitle>Update maintenance ticket</DialogTitle><DialogDescription>{String(edit?.ticketNo ?? "")} · {String(edit?.title ?? "")}</DialogDescription></DialogHeader><div className="grid gap-4 py-5 sm:grid-cols-2"><Field label="Status" required><SelectField name="status" placeholder="Choose status" defaultValue={String(edit?.status ?? "OPEN")} options={statuses} /></Field><Field label="Assigned to"><Input name="assignedTo" defaultValue={String(edit?.assignedTo ?? "")} /></Field><Field label="Actual cost (₹)"><Input name="actualCost" type="number" min="0" step="0.01" defaultValue={String(edit?.actualCost ?? "")} /></Field><Field label="Resolution / work notes" className="sm:col-span-2"><Textarea name="resolution" defaultValue={String(edit?.resolution ?? "")} placeholder="Work completed, parts replaced or reason for hold" /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEdit(null)}>Cancel</Button><Button disabled={pending}>Save ticket update</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
