import { Activity, Banknote, Boxes, CircleDollarSign, HeartPulse, IndianRupee, ShieldCheck, TrendingUp, UsersRound, Wrench } from "lucide-react";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCurrency, MetricCard, OperationsData } from "./shared";

export function ManagementAnalytics({ data }: { data: OperationsData }) {
  const metrics = data.metrics ?? {};
  const fees = Number(metrics.monthlyFees ?? 0);
  const expenses = Number(metrics.monthlyExpenses ?? 0);
  const payroll = Number(metrics.monthlyPayroll ?? 0);
  const operatingOutflow = expenses + payroll;
  const balance = fees - operatingOutflow;
  const staffTotal = Number(metrics.activeStaff ?? 0);
  const staffPresent = Number(metrics.presentStaff ?? 0);
  const staffAttendance = staffTotal ? Math.round((staffPresent / staffTotal) * 100) : 0;
  return <div className="space-y-6 pb-10">
    <section className="relative overflow-hidden rounded-3xl border border-indigo-100 bg-gradient-to-br from-indigo-600 via-violet-600 to-purple-700 p-6 text-white shadow-xl sm:p-8"><div className="absolute -right-24 -top-24 size-80 rounded-full bg-white/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-indigo-100">Management command centre</p><h2 className="mt-3 text-3xl font-black tracking-tight">A live operational view of your school.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100">People, campus safety, finance, health, inventory and maintenance signals are combined here for daily management review.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 p-5 backdrop-blur"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-100">Current-month operating position</p><p className="mt-2 text-3xl font-black">{formatCurrency(balance)}</p><p className="mt-2 text-xs text-indigo-100">Fees collected minus posted expenses and generated payroll.</p></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active students" value={String(metrics.activeStudents ?? 0)} icon={UsersRound} /><MetricCard label="Active staff" value={staffTotal} detail={`${staffAttendance}% marked present today`} icon={Activity} tone="emerald" /><MetricCard label="Visitors on campus" value={String(metrics.activeVisitors ?? 0)} icon={ShieldCheck} tone={Number(metrics.activeVisitors) ? "amber" : "emerald"} /><MetricCard label="Open maintenance" value={String(metrics.openMaintenance ?? 0)} icon={Wrench} tone={Number(metrics.openMaintenance) ? "amber" : "emerald"} /></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Monthly financial snapshot</CardTitle><CardDescription>Operational cash signals for the current calendar month.</CardDescription></CardHeader><CardContent className="space-y-5"><FinanceRow label="Fees collected" value={fees} icon={IndianRupee} tone="text-emerald-700 bg-emerald-50" /><FinanceRow label="School expenses" value={expenses} icon={CircleDollarSign} tone="text-amber-700 bg-amber-50" /><FinanceRow label="Generated payroll" value={payroll} icon={Banknote} tone="text-indigo-700 bg-indigo-50" /><div className="flex items-center justify-between border-t pt-5"><div><p className="font-semibold">Operating position</p><p className="text-xs text-muted-foreground">Before other accruals and outstanding liabilities</p></div><p className={`text-xl font-black ${balance >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{formatCurrency(balance)}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Attention required</CardTitle><CardDescription>Items that may need management action today.</CardDescription></CardHeader><CardContent className="space-y-3"><Attention label="Pending staff leave" value={Number(metrics.pendingLeave ?? 0)} icon={UsersRound} /><Attention label="Low-stock inventory" value={Number(metrics.lowStock ?? 0)} icon={Boxes} /><Attention label="Health visits this month" value={Number(metrics.healthVisits ?? 0)} icon={HeartPulse} neutral /><Attention label="Open maintenance" value={Number(metrics.openMaintenance ?? 0)} icon={Wrench} /></CardContent></Card></div>
  </div>;
}

function FinanceRow({ label, value, icon: Icon, tone }: { label: string; value: number; icon: typeof IndianRupee; tone: string }) { return <div className="flex items-center justify-between gap-4 rounded-2xl border p-4"><div className="flex items-center gap-3"><div className={`flex size-10 items-center justify-center rounded-xl ${tone}`}><Icon className="size-4" /></div><p className="font-semibold">{label}</p></div><p className="text-lg font-black">{formatCurrency(value)}</p></div>; }
function Attention({ label, value, icon: Icon, neutral }: { label: string; value: number; icon: typeof TrendingUp; neutral?: boolean }) { return <div className="flex items-center justify-between rounded-2xl border p-4"><div className="flex items-center gap-3"><Icon className={`size-5 ${!neutral && value ? "text-amber-600" : "text-muted-foreground"}`} /><span className="text-sm font-medium">{label}</span></div><span className={`text-lg font-black ${!neutral && value ? "text-amber-700" : ""}`}>{value}</span></div>; }
