"use client";

import { useMemo, useState } from "react";
import { Ban, CheckCircle2, KeyRound, Search, ShieldCheck, UserCheck, UserRoundCheck } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { SearchableStudentSelect } from "@/components/common/select/SearchableStudentSelect";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EmptyPanel, Field, formatDate, formatDateTime, MetricCard, nested, OperationsData, Row, SelectField, StatusBadge, titleCase, useOperationMutation } from "./shared";

export function PickupManager({ data }: { data: OperationsData }) {
  const { pending, mutate, submit } = useOperationMutation();
  const rows = useMemo(() => data.authorizations ?? [], [data.authorizations]);
  const [studentId, setStudentId] = useState("");
  const [query, setQuery] = useState("");
  const [verify, setVerify] = useState<Row | null>(null);
  const [revoke, setRevoke] = useState<Row | null>(null);
  const active = rows.filter((row) => row.status === "ACTIVE").length;
  const used = rows.filter((row) => row.lastUsedAt).length;
  const filtered = useMemo(() => rows.filter((row) => `${row.pickupCode} ${nested(row, "student", "fullName")} ${row.authorizedName} ${row.phone} ${row.relationship}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
  const today = new Date().toISOString().slice(0, 10);
  return <div className="space-y-6 pb-10">
    <section className="rounded-3xl border border-violet-100 bg-gradient-to-br from-white via-violet-50/60 to-indigo-50/50 p-6 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-700">Safe dismissal</p><h2 className="mt-3 text-2xl font-bold">Release every student only to an authorized person.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Create time-bound or recurring authorizations, verify the pickup code at the gate and maintain a record of every use or revocation.</p></div><div className="grid grid-cols-2 gap-3"><MetricCard label="Active passes" value={active} icon={ShieldCheck} tone="emerald" /><MetricCard label="Pickups recorded" value={used} icon={UserCheck} /></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><Card><CardHeader><CardTitle>New pickup authorization</CardTitle><CardDescription>Confirm the authorized person’s details before issuing the code.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => submit("AUTHORIZE_PICKUP", event, { studentId }, "Pickup authorization created.")}><Field label="Student" required><SearchableStudentSelect value={studentId} onChange={setStudentId} academicYearId={data.academicYearId ?? undefined} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Authorized person" required className="sm:col-span-2"><Input name="authorizedName" minLength={2} maxLength={160} required placeholder="Full name as shown on ID" /></Field><Field label="Relationship" required><SelectField name="relationship" placeholder="Choose relationship" options={["FATHER", "MOTHER", "GUARDIAN", "GRANDPARENT", "SIBLING", "RELATIVE", "DRIVER", "OTHER"].map((value) => ({ value, label: titleCase(value) }))} /></Field><Field label="Mobile number" required><Input name="phone" type="tel" minLength={7} maxLength={24} required /></Field><Field label="Valid from" required><Input name="validFrom" type="date" defaultValue={today} required /></Field><Field label="Valid until"><Input name="validUntil" type="date" /></Field></div><label className="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" name="recurring" className="mt-0.5 size-4" /><span><span className="block text-sm font-semibold">Recurring authorization</span><span className="block text-xs text-muted-foreground">Allow repeated pickups during the validity period.</span></span></label><Field label="Approval notes"><Textarea name="notes" maxLength={500} placeholder="ID verified by, restrictions or dismissal instructions" /></Field><Button className="w-full" disabled={pending || !studentId}><KeyRound className="size-4" />Issue pickup authorization</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Authorization register</CardTitle><CardDescription>Search by code, student or authorized person.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search pickup passes" /></div>{!filtered.length ? <EmptyPanel title="No pickup authorizations" description="Issue the first authorization or change the search." /> : <div className="space-y-3">{filtered.map((row) => <div key={String(row.id)} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><UserRoundCheck className="size-5" /></div><div><p className="font-bold">{nested(row, "student", "fullName")}</p><p className="text-sm text-muted-foreground">{String(row.authorizedName)} · {titleCase(row.relationship)} · {String(row.phone)}</p></div></div><StatusBadge value={row.status} /></div><div className="mt-4 grid gap-2 border-t pt-4 text-xs text-muted-foreground sm:grid-cols-3"><span>Code <strong className="font-mono text-foreground">{String(row.pickupCode)}</strong></span><span>{formatDate(row.validFrom)} – {formatDate(row.validUntil)}</span><span>{row.recurring ? "Recurring" : "One-time / controlled"}</span></div>{row.lastUsedAt ? <Badge className="mt-3" variant="outline">Last used {formatDateTime(row.lastUsedAt)}</Badge> : null}{row.status === "ACTIVE" ? <div className="mt-4 flex gap-2"><Button size="sm" onClick={() => setVerify(row)}><CheckCircle2 className="size-4" />Verify & record pickup</Button><Button size="sm" variant="outline" onClick={() => setRevoke(row)}><Ban className="size-4" />Revoke</Button></div> : null}</div>)}</div>}</CardContent></Card></div>
    <Dialog open={Boolean(verify)} onOpenChange={(open) => { if (!open) setVerify(null); }}><DialogContent><DialogHeader><DialogTitle>Verify pickup authorization</DialogTitle><DialogDescription>Match the code and authorized person’s ID before releasing the student.</DialogDescription></DialogHeader><div className="space-y-3 rounded-2xl border bg-muted/20 p-4"><p className="text-center font-mono text-2xl font-black tracking-widest">{String(verify?.pickupCode ?? "")}</p><div className="border-t pt-3 text-sm"><p><strong>Student:</strong> {verify ? nested(verify, "student", "fullName") : ""}</p><p><strong>Pickup person:</strong> {String(verify?.authorizedName ?? "")} · {String(verify?.phone ?? "")}</p></div></div><DialogFooter><Button variant="outline" onClick={() => setVerify(null)}>Cancel</Button><Button disabled={pending} onClick={() => verify && mutate("UPDATE_PICKUP", { id: verify.id, action: "USE" }, { success: "Student pickup recorded.", after: () => setVerify(null) })}>Confirm pickup</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(revoke)} onOpenChange={(open) => { if (!open) setRevoke(null); }}><DialogContent><DialogHeader><DialogTitle>Revoke this authorization?</DialogTitle><DialogDescription>The pickup code for {revoke ? nested(revoke, "student", "fullName") : "this student"} will stop working immediately.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setRevoke(null)}>Cancel</Button><Button variant="destructive" disabled={pending} onClick={() => revoke && mutate("UPDATE_PICKUP", { id: revoke.id, action: "REVOKE" }, { success: "Pickup authorization revoked.", after: () => setRevoke(null) })}>Revoke authorization</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
